[Login]
#user = anoushey.shah012@outlook.com
#password = FunnelBeam12345
#user = shehnaz.khatun012@gmail.com
#password = FunnelBeam12345
user = naz665564@gmail.com
password = Pakistan@1234*@!
#user = m.imransaeed012@gmail.com
#password = FunnelBeam123
#user = abihanoor710@gmail.com
#password = 09098760

[input]
input_file = query.txt

[output]
output_file = Sample_Company_Output.csv

[PageLimit]
start_page = 1
end_page = 100
